;; systemd-helper configuration definitions
;; by don lindsay (c)2014
;; emacs boilerplate
;; gpl2 boilerplate
;; hammertime

(defun mx/systemd-config () ; pass config-item here
  "Main systemd configuration definition."
  (interactive)
  (message "Configure something about systemd."))
  
(defvar config-item 'unit "Systemd configuration item.")
    
(defvar unit (Description-STRING )
  (Documentation-OTHER )
  (SourcePath-PATH )
  (Requires-UNIT )
  (RequiresOverridable-UNIT ) 
  (Requisite-UNIT ) 
  (RequisiteOverridable-UNIT )
  (Wants-UNIT )
  (BindsTo-UNIT )
  (BindTo-UNIT ) 
  (Conflicts-UNIT ) 
  (Before-UNIT )
  (After-UNIT )
  (OnFailure-UNIT )
  (PropagatesReloadTo-UNIT )
  (PropagateReloadTo-UNIT )
  (ReloadPropagatedFrom-UNIT ) 
  (PropagateReloadFrom-UNIT ) 
  (PartOf-UNIT )
  (RequiresMountsFor-PATH )
  (StopWhenUnneeded-BOOLEAN )
  (RefuseManualStart-BOOLEAN )
  (RefuseManualStop-BOOLEAN )
  (AllowIsolate-BOOLEAN )
  (DefaultDependencies-BOOLEAN )
  (OnFailureIsolate-BOOLEAN )
  (IgnoreOnIsolate-BOOLEAN )
  (IgnoreOnSnapshot-BOOLEAN )
  (JobTimeoutSec-SECONDS )
  (ConditionPathExists-CONDITION )
  (ConditionPathExistsGlob-CONDITION )
  (ConditionPathIsDirectory-CONDITION )
  (ConditionPathIsSymbolicLink-CONDITION )
  (ConditionPathIsMountPoint-CONDITION )
  (ConditionPathIsReadWrite-CONDITION )
  (ConditionDirectoryNotEmpty-CONDITION )
  (ConditionFileNotEmpty-CONDITION )
  (ConditionFileIsExecutable-CONDITION )
  (ConditionKernelCommandLine-CONDITION )
  (ConditionVirtualization-CONDITION )
  (ConditionSecurity-CONDITION )
  (ConditionCapability-CONDITION )
  (ConditionHost-CONDITION )
  (ConditionACPower-CONDITION )
  (ConditionNull-CONDITION )

(defvar mx-systemd-service 'pidfile-PATH 
  "Systemd Service configuration item."
  (configuration-item (Service )
		      (Service (PIDFile-PATH )
			       (ExecStartPre-PATH-ARGUMENT )
			       (ExecStart-PATH-ARGUMENT )
			       (ExecStartPost-PATH-ARGUMENT )
			       (ExecReload-PATH-ARGUMENT )
			       (ExecStop-PATH-ARGUMENT )
			       (ExecStopPost-PATH-ARGUMENT )
			       (RestartSec-SECONDS )
			       (TimeoutSec-OTHER )
			       (TimeoutStartSec-OTHER )
			       (TimeoutStopSec-OTHER )
			       (WatchdogSec-SECONDS )
			       (StartLimitInterval-SECONDS )
			       (StartLimitBurst-UNSIGNED )
			       (StartLimitAction-OTHER )
			       (Type-SERVICETYPE )
			       (Restart-SERVICERESTART )
			       (PermissionsStartOnly-BOOLEAN )
			       (RootDirectoryStartOnly-BOOLEAN )
			       (RemainAfterExit-BOOLEAN )
			       (GuessMainPID-BOOLEAN )
			       (RestartPreventExitStatus-OTHER )
			       (SuccessExitStatus-OTHER )
			       (SysVStartPriority-SYSVPRIORITY )
			       (NonBlocking-BOOLEAN )
			       (BusName-STRING )
			       (NotifyAccess-ACCESS )
			       (Sockets-OTHER )
			       (FsckPassNo-OTHER ) 
			       (WorkingDirectory-PATH )
			       (RootDirectory-PATH )
			       (User-STRING )
			       (Group-STRING )
			       (SupplementaryGroups-STRING )
			       (Nice-NICE )
			       (OOMScoreAdjust-OOMSCOREADJUST )
			       (IOSchedulingClass-IOCLASS )
			       (IOSchedulingPriority-IOPRIORITY )
			       (CPUSchedulingPolicy-CPUSCHEDPOLICY )
			       (CPUSchedulingPriority-CPUSCHEDPRIO )
			       (CPUSchedulingResetOnFork-BOOLEAN )
			       (CPUAffinity-CPUAFFINITY )
			       (UMask-MODE )
			       (Environment-OTHER )
			       (EnvironmentFile-FILE )
			       (StandardInput-INPUT )
			       (StandardOutput-OUTPUT )
			       (StandardError-OUTPUT )
			       (TTYPath-PATH )
			       (TTYReset-BOOLEAN )
			       (TTYVHangup-BOOLEAN )
			       (TTYVTDisallocate-BOOLEAN )
			       (SyslogIdentifier-STRING )
			       (SyslogFacility-FACILITY )
			       (SyslogLevel-LEVEL )
			       (SyslogLevelPrefix-BOOLEAN ) 
			       (Capabilities-CAPABILITIES )
			       (SecureBits-SECUREBITS )
			       (CapabilityBoundingSet-BOUNDINGSET )
			       (TimerSlackNSec-NANOSECONDS )
			       (NoNewPrivileges-BOOLEAN )
			       (SystemCallFilter-OTHER )
			       (LimitCPU-LIMIT )
			       (LimitFSIZE-LIMIT )
			       (LimitDATA-LIMIT )
			       (LimitSTACK-LIMIT )
			       (LimitCORE-LIMIT )
			       (LimitRSS-LIMIT )
			       (LimitNOFILE-LIMIT )
			       (LimitAS-LIMIT )
			       (LimitNPROC-LIMIT )
			       (LimitMEMLOCK-LIMIT )
			       (LimitLOCKS-LIMIT )
			       (LimitSIGPENDING-LIMIT ) 
			       (LimitMSGQUEUE-LIMIT )
			       (LimitNICE-LIMIT ) 
			       (LimitRTPRIO-LIMIT )
			       (LimitRTTIME-LIMIT )
			       (ControlGroup-CGROUP )
			       (ControlGroupAttribute-OTHER )
			       (CPUShares-OTHER )
			       (MemoryLimit-OTHER )
			       (MemorySoftLimit-OTHER )
			       (DeviceAllow-OTHER )
			       (DeviceDeny-OTHER )
			       (BlockIOWeight-OTHER )
			       (BlockIOReadBandwidth-OTHER )
			       (BlockIOWriteBandwidth-OTHER )
			       (ReadWriteDirectories-PATH )
			       (ReadOnlyDirectories-PATH )
			       (InaccessibleDirectories-PATH )
			       (PrivateTmp-BOOLEAN )
			       (PrivateNetwork-BOOLEAN )
			       (MountFlags-MOUNTFLAG )
			       (TCPWrapName-STRING )
			       (PAMName-STRING )
			       (IgnoreSIGPIPE-BOOLEAN )
			       (UtmpIdentifier-STRING )
			       (ControlGroupModify-BOOLEAN )
			       (ControlGroupPersistent-OTHER )
			       (SendSIGKILL-BOOLEAN )
			       (KillMode-KILLMODE )
			       (KillSignal-SIGNAL )

(defvar mx-systemd-socket 'listenstream-socket 
  "Systemd Socket configuration item"
  (ListenDatagram-SOCKET )
  (ListenSequentialPacket-SOCKET ) 
  (ListenFIFO-SOCKET ) 
  (ListenNetlink-SOCKET ) 
  (ListenSpecial-SOCKET )
  (ListenMessageQueue-SOCKET )
  (BindIPv6Only-SOCKETBIND )
  (Backlog-UNSIGNED )
  (BindToDevice-NETWORKINTERFACE )
  (ExecStartPre-PATH-ARGUMENT )
  (ExecStartPost-PATH-ARGUMENT )
  (ExecStopPre-PATH-ARGUMENT )
  (ExecStopPost-PATH-ARGUMENT )
  (TimeoutSec-SECONDS )
  (DirectoryMode-MODE )
  (SocketMode-MODE )
  (Accept-BOOLEAN )
  (MaxConnections-UNSIGNED )
  (KeepAlive-BOOLEAN )
  (Priority-INTEGER )
  (ReceiveBuffer-SIZE )
  (SendBuffer-SIZE )
  (IPTOS-TOS )
  (IPTTL-INTEGER )
  (Mark-INTEGER )
  (PipeSize-SIZE )
  (FreeBind-BOOLEAN )
  (Transparent-BOOLEAN )
  (Broadcast-BOOLEAN )
  (PassCredentials-BOOLEAN )
  (PassSecurity-BOOLEAN )
  (TCPCongestion-STRING )
  (MessageQueueMaxMessages-OTHER )
  (MessageQueueMessageSize-OTHER )
  (Service-OTHER )
  (SmackLabel-STRING )
  (SmackLabelIPIn-STRING )
  (SmackLabelIPOut-STRING )
  (WorkingDirectory-PATH )
  (RootDirectory-PATH )
  (User-STRING )
  (Group-STRING )
  (SupplementaryGroups-STRING ) 
  (Nice-NICE )
  (OOMScoreAdjust-OOMSCOREADJUST )
  (IOSchedulingClass-IOCLASS )
  (IOSchedulingPriority-IOPRIORITY )
  (CPUSchedulingPolicy-CPUSCHEDPOLICY )
  (CPUSchedulingPriority-CPUSCHEDPRIO )
  (CPUSchedulingResetOnFork-BOOLEAN )
  (CPUAffinity-CPUAFFINITY )
  (UMask-MODE )
  (Environment-OTHER )
  (EnvironmentFile-FILE )
  (StandardInput-INPUT )
  (StandardOutput-OUTPUT )
  (StandardError-OUTPUT )
  (TTYPath-PATH )
  (TTYReset-BOOLEAN )
  (TTYVHangup-BOOLEAN )
  (TTYVTDisallocate-BOOLEAN )
  (SyslogIdentifier-STRING )
  (SyslogFacility-FACILITY )
  (SyslogLevel-LEVEL )
  (SyslogLevelPrefix-BOOLEAN )
  (Capabilities-CAPABILITIES )
  (SecureBits-SECUREBITS )
  (CapabilityBoundingSet-BOUNDINGSET )
  (TimerSlackNSec-NANOSECONDS )
  (NoNewPrivileges-BOOLEAN )
  (SystemCallFilter-OTHER )  
  (LimitCPU-LIMIT )
  (LimitFSIZE-LIMIT )
  (LimitDATA-LIMIT )
  (LimitSTACK-LIMIT )
  (LimitCORE-LIMIT )
  (LimitRSS-LIMIT )
  (LimitNOFILE-LIMIT )
  (LimitAS-LIMIT )
  (LimitNPROC-LIMIT )
  (LimitMEMLOCK-LIMIT )
  (LimitLOCKS-LIMIT )
  (LimitSIGPENDING-LIMIT )
  (LimitMSGQUEUE-LIMIT )
  (LimitNICE-LIMIT ) 
  (LimitRTPRIO-LIMIT )
  (LimitRTTIME-LIMIT )
  (ControlGroup-CGROUP ) 
  (ControlGroupAttribute-OTHER )
  (CPUShares-OTHER )
  (MemoryLimit-OTHER )
  (MemorySoftLimit-OTHER )
  (DeviceAllow-OTHER )
  (DeviceDeny-OTHER )
  (BlockIOWeight-OTHER )
  (BlockIOReadBandwidth-OTHER )
  (BlockIOWriteBandwidth-OTHER ) 
  (ReadWriteDirectories-PATH )
  (ReadOnlyDirectories-PATH )
  (InaccessibleDirectories-PATH ) 
  (PrivateTmp-BOOLEAN )
  (PrivateNetwork-BOOLEAN )
  (MountFlags-MOUNTFLAG ) 
  (TCPWrapName-STRING )
  (PAMName-STRING )
  (IgnoreSIGPIPE-BOOLEAN )
  (UtmpIdentifier-STRING )
  (ControlGroupModify-BOOLEAN )
  (ControlGroupPersistent-OTHER )
  (SendSIGKILL-BOOLEAN )
  (KillMode-KILLMODE )
  (KillSignal-SIGNAL )
    
(defvar mx-systemd-mount 'what-STRING 
  "Systemd Mount configuration item."
  (configuration-item (Mount )
		      (Mount (What-STRING )
			     (Where-PATH )
			     (Options-STRING )
			     (Type-STRING )
			     (FsckPassNo-OTHER )
			     (TimeoutSec-SECONDS )
			     (DirectoryMode-MODE )
			     (WorkingDirectory-PATH )
			     (RootDirectory-PATH )
			     (User-STRING )
			     (Group-STRING )
			     (SupplementaryGroups-STRING )
			     (Nice-NICE )
			     (OOMScoreAdjust-OOMSCOREADJUST )
			     (IOSchedulingClass-IOCLASS )
			     (IOSchedulingPriority-IOPRIORITY )
			     (CPUSchedulingPolicy-CPUSCHEDPOLICY )
			     (CPUSchedulingPriority-CPUSCHEDPRIO )
			     (CPUSchedulingResetOnFork-BOOLEAN )
			     (CPUAffinity-CPUAFFINITY )
			     (UMask-MODE )
			     (Environment-OTHER )
			     (EnvironmentFile-FILE )
			     (StandardInput-INPUT )
			     (StandardOutput-OUTPUT )
			     (StandardError-OUTPUT )
			     (TTYPath-PATH )
			     (TTYReset-BOOLEAN )
			     (TTYVHangup-BOOLEAN )
			     (TTYVTDisallocate-BOOLEAN )
			     (SyslogIdentifier-STRING )
			     (SyslogFacility-FACILITY )
			     (SyslogLevel-LEVEL )
			     (SyslogLevelPrefix-BOOLEAN )
			     (Capabilities-CAPABILITIES )
			     (SecureBits-SECUREBITS )
			     (CapabilityBoundingSet-BOUNDINGSET )
			     (TimerSlackNSec-NANOSECONDS )
			     (NoNewPrivileges-BOOLEAN )
			     (SystemCallFilter-OTHER )
			     (LimitCPU-LIMIT )
			     (LimitFSIZE-LIMIT )
			     (LimitDATA-LIMIT )
			     (LimitSTACK-LIMIT )
			     (LimitCORE-LIMIT )
			     (LimitRSS-LIMIT )
			     (LimitNOFILE-LIMIT )
			     (LimitAS-LIMIT )
			     (LimitNPROC-LIMIT )
			     (LimitMEMLOCK-LIMIT )
			     (LimitLOCKS-LIMIT )
			     (LimitSIGPENDING-LIMIT )
			     (LimitMSGQUEUE-LIMIT )
			     (LimitNICE-LIMIT )
			     (LimitRTPRIO-LIMIT )
			     (LimitRTTIME-LIMIT )
			     (ControlGroup-CGROUP )
			     (ControlGroupAttribute-OTHER )
			     (CPUShares-OTHER )
			     (MemoryLimit-OTHER )
			     (MemorySoftLimit-OTHER )
			     (DeviceAllow-OTHER )
			     (DeviceDeny-OTHER )
			     (BlockIOWeight-OTHER )
			     (BlockIOReadBandwidth-OTHER )
			     (BlockIOWriteBandwidth-OTHER ) 
			     (ReadWriteDirectories-PATH )
			     (ReadOnlyDirectories-PATH )
			     (InaccessibleDirectories-PATH )
			     (PrivateTmp-BOOLEAN )
			     (PrivateNetwork-BOOLEAN )
			     (MountFlags-MOUNTFLAG ) 
			     (TCPWrapName-STRING )
			     (PAMName-STRING ) 
			     (IgnoreSIGPIPE-BOOLEAN )
			     (UtmpIdentifier-STRING )
			     (ControlGroupModify-BOOLEAN )
			     (ControlGroupPersistent-OTHER )
			     (SendSIGKILL-BOOLEAN )
			     (KillMode-KILLMODE )
			     (KillSignal-SIGNAL )
			     
(defvar ms-systemd-automount 'where-PATH 
  "Systemd Automount configuration item."
  (configuration-item (Automount )
		      (Automount (Where-PATH )
				 (DirectoryMode-MODE )
				 
(defvar ms-systemd-swap 'what-PATH 
  "Systemd Swap configuration item."				 
  (configuration-item (Swap )
		      (Swap (What-PATH )
			    (Priority-INTEGER )
			    (TimeoutSec-SECONDS )
			    (WorkingDirectory-PATH )
			    (RootDirectory-PATH )
			    (User-STRING )
			    (Group-STRING )
			    (SupplementaryGroups-STRING )
			    (Nice-NICE )
			    (OOMScoreAdjust-OOMSCOREADJUST )
			    (IOSchedulingClass-IOCLASS )
			    (IOSchedulingPriority-IOPRIORITY )
			    (CPUSchedulingPolicy-CPUSCHEDPOLICY )
			    (CPUSchedulingPriority-CPUSCHEDPRIO )
			    (CPUSchedulingResetOnFork-BOOLEAN )
			    (CPUAffinity-CPUAFFINITY )
			    (UMask-MODE )
			    (Environment-OTHER )
			    (EnvironmentFile-FILE )
			    (StandardInput-INPUT )
			    (StandardOutput-OUTPUT )
			    (StandardError-OUTPUT )
			    (TTYPath-PATH )
			    (TTYReset-BOOLEAN )
			    (TTYVHangup-BOOLEAN )
			    (TTYVTDisallocate-BOOLEAN )
			    (SyslogIdentifier-STRING )
			    (SyslogFacility-FACILITY )
			    (SyslogLevel-LEVEL )
			    (SyslogLevelPrefix-BOOLEAN )
			    (Capabilities-CAPABILITIES )
			    (SecureBits-SECUREBITS )
			    (CapabilityBoundingSet-BOUNDINGSET )
			    (TimerSlackNSec-NANOSECONDS )
			    (NoNewPrivileges-BOOLEAN )
			    (SystemCallFilter-OTHER )
			    (LimitCPU-LIMIT )
			    (LimitFSIZE-LIMIT )
			    (LimitDATA-LIMIT )
			    (LimitSTACK-LIMIT )
			    (LimitCORE-LIMIT )
			    (LimitRSS-LIMIT )
			    (LimitNOFILE-LIMIT )
			    (LimitAS-LIMIT )
			    (LimitNPROC-LIMIT )
			    (LimitMEMLOCK-LIMIT )
			    (LimitLOCKS-LIMIT )
			    (LimitSIGPENDING-LIMIT )
			    (LimitMSGQUEUE-LIMIT )
			    (LimitNICE-LIMIT )
			    (LimitRTPRIO-LIMIT )
			    (LimitRTTIME-LIMIT )
			    (ControlGroup-CGROUP )
			    (ControlGroupAttribute-OTHER )
			    (CPUShares-OTHER )
			    (MemoryLimit-OTHER )
			    (MemorySoftLimit-OTHER )
			    (DeviceAllow-OTHER )
			    (DeviceDeny-OTHER )
			    (BlockIOWeight-OTHER )
			    (BlockIOReadBandwidth-OTHER )
			    (BlockIOWriteBandwidth-OTHER )
			    (ReadWriteDirectories-PATH ) 
			    (ReadOnlyDirectories-PATH )
			    (InaccessibleDirectories-PATH )
			    (PrivateTmp-BOOLEAN )
			    (PrivateNetwork-BOOLEAN )
			    (MountFlags-MOUNTFLAG )
			    (TCPWrapName-STRING )
			    (PAMName-STRING )
			    (IgnoreSIGPIPE-BOOLEAN )
			    (UtmpIdentifier-STRING )
			    (ControlGroupModify-BOOLEAN )
			    (ControlGroupPersistent-OTHER )
			    (SendSIGKILL-BOOLEAN )
			    (KillMode-KILLMODE )
			    (KillSignal-SIGNAL )

(defvar mx-systemd-timer 'oncalendar-TIMER 
  "Systemd Timer configuration item."
  (configuration-item (Timer )
		      (Timer (OnCalendar-TIMER )
			     (OnActiveSec-TIMER )
			     (OnBootSec-TIMER )
			     (OnStartupSec-TIMER )
			     (OnUnitActiveSec-TIMER ) 
			     (OnUnitInactiveSec-TIMER )
			     (Unit-UNIT )

(defvar mx-systemd-path 'pathexists-PATH 
  "Systemd PATH configuration items."
  (configuration-item (Path )
		      (Path (PathExists-PATH )
			    (PathExistsGlob-PATH )
			    (PathChanged-PATH )
			    (PathModified-PATH )
			    (DirectoryNotEmpty-PATH )
			    (Unit-UNIT )
			    (MakeDirectory-BOOLEAN )
			    (DirectoryMode-MODE )

(defvar ms-systemd-install 'alias-OTHER 
  "Systemd Install configuration item."
  (configuration-item (Install )
		      (Install (Alias-OTHER )
			       (WantedBy-OTHER )
			       (RequiredBy-OTHER )
			       (Also-OTHER )
    
